name: Deploy

permissions:
  contents: read

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to render
        run: |
          curl -f -X "POST" ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
